// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.3
// source: marketcenter/v1/marketcenter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrencyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CurrencyListRequest) Reset() {
	*x = CurrencyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketcenter_v1_marketcenter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyListRequest) ProtoMessage() {}

func (x *CurrencyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketcenter_v1_marketcenter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyListRequest.ProtoReflect.Descriptor instead.
func (*CurrencyListRequest) Descriptor() ([]byte, []int) {
	return file_marketcenter_v1_marketcenter_proto_rawDescGZIP(), []int{0}
}

func (x *CurrencyListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CurrencyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Price       string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	QuoteChange string `protobuf:"bytes,3,opt,name=quoteChange,proto3" json:"quoteChange,omitempty"`
}

func (x *CurrencyReply) Reset() {
	*x = CurrencyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketcenter_v1_marketcenter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyReply) ProtoMessage() {}

func (x *CurrencyReply) ProtoReflect() protoreflect.Message {
	mi := &file_marketcenter_v1_marketcenter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyReply.ProtoReflect.Descriptor instead.
func (*CurrencyReply) Descriptor() ([]byte, []int) {
	return file_marketcenter_v1_marketcenter_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CurrencyReply) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *CurrencyReply) GetQuoteChange() string {
	if x != nil {
		return x.QuoteChange
	}
	return ""
}

type CurrencyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount int64            `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Currencies []*CurrencyReply `protobuf:"bytes,2,rep,name=Currencies,proto3" json:"Currencies,omitempty"`
}

func (x *CurrencyListResponse) Reset() {
	*x = CurrencyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_marketcenter_v1_marketcenter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrencyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyListResponse) ProtoMessage() {}

func (x *CurrencyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketcenter_v1_marketcenter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyListResponse.ProtoReflect.Descriptor instead.
func (*CurrencyListResponse) Descriptor() ([]byte, []int) {
	return file_marketcenter_v1_marketcenter_proto_rawDescGZIP(), []int{2}
}

func (x *CurrencyListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CurrencyListResponse) GetCurrencies() []*CurrencyReply {
	if x != nil {
		return x.Currencies
	}
	return nil
}

var File_marketcenter_v1_marketcenter_proto protoreflect.FileDescriptor

var file_marketcenter_v1_marketcenter_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x13, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x5d, 0x0a, 0x0d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22,
	0x76, 0x0a, 0x14, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0a, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x0a, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x69, 0x65, 0x73, 0x32, 0x86, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x76, 0x0a, 0x0c, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74,
	0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x61, 0x77, 0x6e, 0x33, 0x30, 0x33, 0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x63, 0x65, 0x6e, 0x74,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_marketcenter_v1_marketcenter_proto_rawDescOnce sync.Once
	file_marketcenter_v1_marketcenter_proto_rawDescData = file_marketcenter_v1_marketcenter_proto_rawDesc
)

func file_marketcenter_v1_marketcenter_proto_rawDescGZIP() []byte {
	file_marketcenter_v1_marketcenter_proto_rawDescOnce.Do(func() {
		file_marketcenter_v1_marketcenter_proto_rawDescData = protoimpl.X.CompressGZIP(file_marketcenter_v1_marketcenter_proto_rawDescData)
	})
	return file_marketcenter_v1_marketcenter_proto_rawDescData
}

var file_marketcenter_v1_marketcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_marketcenter_v1_marketcenter_proto_goTypes = []interface{}{
	(*CurrencyListRequest)(nil),  // 0: marketcenter.v1.CurrencyListRequest
	(*CurrencyReply)(nil),        // 1: marketcenter.v1.CurrencyReply
	(*CurrencyListResponse)(nil), // 2: marketcenter.v1.CurrencyListResponse
}
var file_marketcenter_v1_marketcenter_proto_depIdxs = []int32{
	1, // 0: marketcenter.v1.CurrencyListResponse.Currencies:type_name -> marketcenter.v1.CurrencyReply
	0, // 1: marketcenter.v1.MarketCenter.CurrencyList:input_type -> marketcenter.v1.CurrencyListRequest
	2, // 2: marketcenter.v1.MarketCenter.CurrencyList:output_type -> marketcenter.v1.CurrencyListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketcenter_v1_marketcenter_proto_init() }
func file_marketcenter_v1_marketcenter_proto_init() {
	if File_marketcenter_v1_marketcenter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_marketcenter_v1_marketcenter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketcenter_v1_marketcenter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_marketcenter_v1_marketcenter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrencyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_marketcenter_v1_marketcenter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketcenter_v1_marketcenter_proto_goTypes,
		DependencyIndexes: file_marketcenter_v1_marketcenter_proto_depIdxs,
		MessageInfos:      file_marketcenter_v1_marketcenter_proto_msgTypes,
	}.Build()
	File_marketcenter_v1_marketcenter_proto = out.File
	file_marketcenter_v1_marketcenter_proto_rawDesc = nil
	file_marketcenter_v1_marketcenter_proto_goTypes = nil
	file_marketcenter_v1_marketcenter_proto_depIdxs = nil
}
