// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: markets/v1/markets.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *TokenListRequest) Reset() {
	*x = TokenListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_markets_v1_markets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenListRequest) ProtoMessage() {}

func (x *TokenListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_markets_v1_markets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenListRequest.ProtoReflect.Descriptor instead.
func (*TokenListRequest) Descriptor() ([]byte, []int) {
	return file_markets_v1_markets_proto_rawDescGZIP(), []int{0}
}

func (x *TokenListRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type TokenReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token       string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Price       string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	QuoteChange string `protobuf:"bytes,3,opt,name=quoteChange,proto3" json:"quoteChange,omitempty"`
}

func (x *TokenReply) Reset() {
	*x = TokenReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_markets_v1_markets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReply) ProtoMessage() {}

func (x *TokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_markets_v1_markets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReply.ProtoReflect.Descriptor instead.
func (*TokenReply) Descriptor() ([]byte, []int) {
	return file_markets_v1_markets_proto_rawDescGZIP(), []int{1}
}

func (x *TokenReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenReply) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *TokenReply) GetQuoteChange() string {
	if x != nil {
		return x.QuoteChange
	}
	return ""
}

type TokenListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalCount int64         `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	Tokens     []*TokenReply `protobuf:"bytes,2,rep,name=Tokens,proto3" json:"Tokens,omitempty"`
}

func (x *TokenListResponse) Reset() {
	*x = TokenListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_markets_v1_markets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenListResponse) ProtoMessage() {}

func (x *TokenListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_markets_v1_markets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenListResponse.ProtoReflect.Descriptor instead.
func (*TokenListResponse) Descriptor() ([]byte, []int) {
	return file_markets_v1_markets_proto_rawDescGZIP(), []int{2}
}

func (x *TokenListResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *TokenListResponse) GetTokens() []*TokenReply {
	if x != nil {
		return x.Tokens
	}
	return nil
}

var File_markets_v1_markets_proto protoreflect.FileDescriptor

var file_markets_v1_markets_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x5a, 0x0a, 0x0a,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x71, 0x75, 0x6f,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x63, 0x0a, 0x11, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a,
	0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x32, 0x6b, 0x0a,
	0x07, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x60, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x77, 0x6e, 0x33, 0x30, 0x33,
	0x2f, 0x67, 0x6f, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_markets_v1_markets_proto_rawDescOnce sync.Once
	file_markets_v1_markets_proto_rawDescData = file_markets_v1_markets_proto_rawDesc
)

func file_markets_v1_markets_proto_rawDescGZIP() []byte {
	file_markets_v1_markets_proto_rawDescOnce.Do(func() {
		file_markets_v1_markets_proto_rawDescData = protoimpl.X.CompressGZIP(file_markets_v1_markets_proto_rawDescData)
	})
	return file_markets_v1_markets_proto_rawDescData
}

var file_markets_v1_markets_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_markets_v1_markets_proto_goTypes = []any{
	(*TokenListRequest)(nil),  // 0: markets.v1.TokenListRequest
	(*TokenReply)(nil),        // 1: markets.v1.TokenReply
	(*TokenListResponse)(nil), // 2: markets.v1.TokenListResponse
}
var file_markets_v1_markets_proto_depIdxs = []int32{
	1, // 0: markets.v1.TokenListResponse.Tokens:type_name -> markets.v1.TokenReply
	0, // 1: markets.v1.Markets.TokenList:input_type -> markets.v1.TokenListRequest
	2, // 2: markets.v1.Markets.TokenList:output_type -> markets.v1.TokenListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_markets_v1_markets_proto_init() }
func file_markets_v1_markets_proto_init() {
	if File_markets_v1_markets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_markets_v1_markets_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TokenListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_markets_v1_markets_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TokenReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_markets_v1_markets_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TokenListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_markets_v1_markets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_markets_v1_markets_proto_goTypes,
		DependencyIndexes: file_markets_v1_markets_proto_depIdxs,
		MessageInfos:      file_markets_v1_markets_proto_msgTypes,
	}.Build()
	File_markets_v1_markets_proto = out.File
	file_markets_v1_markets_proto_rawDesc = nil
	file_markets_v1_markets_proto_goTypes = nil
	file_markets_v1_markets_proto_depIdxs = nil
}
